passoa = int(input('Pense e digite um numero superior a 10 e inferior a 100:'))
passob = int(passoa*2)
passoc = int(passob+5)
passod = int(passoc*50)
passoano = int(input('Digite o ano atual:'))
passof = int(passoano-250)
passosoma = int(passod+passof)
passoan = int(input('Digite o ano de nascimento:'))
passog = int(passosoma-passoan)
print('Os dois primeiros números é o número digitado, enquanto os ultimos dois são a idade: {}'.format(passog))